# meta
author_introduction: 情報系大学生。Web開発、3DCG、映像制作など。
twitter_id: sititou70
github_id: sititou70
facebook_id: 100010978380334

#ui
latest_articles_num: 5

# other
google_analytics_id: UA-93342312-1
google_analytics_developer_key: sititou70.github.io_developer
twitter_widget_id: '481402935021035520'
theme_path: './themes/sititou70/'

